/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp=Object.defineProperty;var __getOwnPropDesc=Object.getOwnPropertyDescriptor;var __getOwnPropNames=Object.getOwnPropertyNames;var __hasOwnProp=Object.prototype.hasOwnProperty;var __export=(t,e)=>{for(var o in e)__defProp(t,o,{get:e[o],enumerable:!0})};var __copyProps=(t,e,o,r)=>{if(e&&typeof e=="object"||typeof e=="function")for(let n of __getOwnPropNames(e))!__hasOwnProp.call(t,n)&&n!==o&&__defProp(t,n,{get:()=>e[n],enumerable:!(r=__getOwnPropDesc(e,n))||r.enumerable});return t};var __toCommonJS=t=>__copyProps(__defProp({},"__esModule",{value:!0}),t);var e={};__export(e,{default:()=>l});module.exports=__toCommonJS(e);var i=require("obsidian");

/* ==========================================
   默认设置

   关键：revealOnCursor 默认 false
   开启会导致光标移动时标记反复显示/隐藏（横跳闪烁）
   需要稳定隐藏体验的用户保持关闭即可
   ========================================== */
var s={enabled:!0,showStatusBar:!0,showRibbon:!0,hideHeaders:!0,hideBold:!0,hideItalic:!0,hideStrikethrough:!0,hideHighlight:!0,hideLinks:!0,hideCode:!0,hideQuotes:!0,hideLists:!0,hideTask:!0,hideTags:!1,hideHr:!1,hideTable:!1,hideFootnote:!1,hideComment:!1,revealOnCursor:!1,revealOnHover:!1};

/* ==========================================
   设置面板
   ========================================== */
var d=class extends i.PluginSettingTab{constructor(t,e){super(t,e);this.plugin=e}
_toggle(t,e,o,r){new i.Setting(t).setName(e).setDesc(r).addToggle(n=>n.setValue(this.plugin.settings[o]).onChange(async a=>{this.plugin.settings[o]=a,await this.plugin.saveSettings()}))}
display(){var t=this,o=t.containerEl;o.empty();
o.createEl("h1",{text:"Markdown Visibility Enhanced"});
o.createEl("p",{text:"隐藏编辑器中 Markdown 格式标记（# * ** []() 等），让编辑体验更接近阅读视图。",cls:"setting-item-description"});

o.createEl("h2",{text:"总体控制"});
new i.Setting(o).setName("启用标记隐藏").setDesc("全局开关：开启后根据下方设置隐藏 Markdown 格式标记").addToggle(t=>t.setValue(this.plugin.settings.enabled).onChange(async e=>{this.plugin.settings.enabled=e,await this.plugin.saveSettings()}));

o.createEl("h2",{text:"界面选项"});
new i.Setting(o).setName("显示状态栏项").setDesc("在底部状态栏显示当前状态，点击可快速切换").addToggle(t=>t.setValue(this.plugin.settings.showStatusBar).onChange(async e=>{this.plugin.settings.showStatusBar=e,await this.plugin.saveSettings(),e?this.plugin.createStatusBarItem():this.plugin.removeStatusBarItem()}));
new i.Setting(o).setName("显示 Ribbon 图标").setDesc("在左侧边栏显示眼睛图标，点击可快速切换").addToggle(t=>t.setValue(this.plugin.settings.showRibbon).onChange(async e=>{this.plugin.settings.showRibbon=e,await this.plugin.saveSettings()}));

o.createEl("h2",{text:"交互行为（谨慎开启）"});
o.createEl("p",{text:"以下功能开启后可能导致光标移动时标记闪烁。建议保持关闭以获得最稳定的体验。",cls:"setting-item-description"});
new i.Setting(o).setName("悬停显示").setDesc("鼠标悬停在某行时显示该行标记。不影响编辑稳定性。").addToggle(t=>t.setValue(this.plugin.settings.revealOnHover).onChange(async e=>{this.plugin.settings.revealOnHover=e,await this.plugin.saveSettings()}));
new i.Setting(o).setName("光标行显示 ⚠️").setDesc("光标所在行显示标记。可能导致快速移动光标时出现闪烁（横跳），建议关闭。").addToggle(t=>t.setValue(this.plugin.settings.revealOnCursor).onChange(async e=>{this.plugin.settings.revealOnCursor=e,await this.plugin.saveSettings()}));

o.createEl("h2",{text:"隐藏的标记类型"});
o.createEl("p",{text:"选择需要隐藏的标记类型。取消勾选则该类标记保持可见。",cls:"setting-item-description"});
o.createEl("h3",{text:"文本格式"});
this._toggle(o,"标题标记","hideHeaders","隐藏标题前的 # 符号");
this._toggle(o,"加粗标记","hideBold","隐藏 ** 符号");
this._toggle(o,"斜体标记","hideItalic","隐藏 * 或 _ 符号");
this._toggle(o,"删除线标记","hideStrikethrough","隐藏 ~~ 符号");
this._toggle(o,"高亮标记","hideHighlight","隐藏 == 符号");

o.createEl("h3",{text:"链接与代码"});
this._toggle(o,"链接标记","hideLinks","隐藏 []() 链接语法和 URL");
this._toggle(o,"代码标记","hideCode","隐藏 ` 和 ``` 符号");

o.createEl("h3",{text:"块级元素"});
this._toggle(o,"引用标记","hideQuotes","隐藏 > 符号");
this._toggle(o,"列表标记","hideLists","隐藏 - * 和 1. 标记");
this._toggle(o,"任务标记","hideTask","隐藏 [ ] 和 [x] 标记");

o.createEl("h3",{text:"扩展标记"});
this._toggle(o,"标签标记","hideTags","隐藏 #tag 中的 #");
this._toggle(o,"水平线标记","hideHr","隐藏 --- 分隔符");
this._toggle(o,"表格标记","hideTable","隐藏 | 分隔符");
this._toggle(o,"脚注标记","hideFootnote","隐藏 [^1] 标记");

o.createEl("h2",{text:"快捷键"});
var r=o.createEl("div",{cls:"setting-item-description"});
r.createEl("p",{text:"可在 设置 → 快捷键 中配置："});
var n=r.createEl("ul");
n.createEl("li",{text:"切换 Markdown 标记可见性 — 主要开关"});
n.createEl("li",{text:"切换光标行显示 — 开启/关闭光标行标记显示"});
n.createEl("li",{text:"切换悬停显示 — 开启/关闭鼠标悬停标记显示"});

o.createEl("h2",{text:"关于"});
o.createEl("p",{text:"基于 miztizm/obsidian-markdown-visibility 优化。核心改进：color:transparent（稳定无跳动）、移除 letter-spacing 和 font-size:0（消除布局偏移）、默认关闭光标行显示（杜绝横跳闪烁）。",cls:"setting-item-description"})}};

/* ==========================================
   主插件类
   ========================================== */
var l=class extends i.Plugin{constructor(t,e){super(t,e);this._debounceTimer=null;this._statusBarItem=null;this._ribbonIcon=null}
async onload(){await this.loadSettings(),this.settings.showStatusBar&&this.createStatusBarItem(),this.settings.showRibbon&&this.createRibbonIcon(),this.addCommand({id:"toggle-markdown-visibility",name:"切换 Markdown 标记可见性",callback:()=>this.toggleVisibility()}),this.addCommand({id:"toggle-cursor-reveal",name:"切换光标行显示",callback:()=>this.toggleCursorReveal()}),this.addCommand({id:"toggle-hover-reveal",name:"切换悬停显示",callback:()=>this.toggleHoverReveal()}),this.addSettingTab(new d(this.app,this)),this.applyStyles(),this.registerEvent(this.app.workspace.on("css-change",()=>{this.refreshStyles()})),this.registerEvent(this.app.workspace.on("layout-change",()=>{this.debouncedRefreshStyles()})),console.log("Markdown Visibility Enhanced: loaded")}
onunload(){this.removeStyles(),this.removeStatusBarItem(),this.removeRibbonIcon(),this._debounceTimer&&clearTimeout(this._debounceTimer)}
async loadSettings(){this.settings=Object.assign({},s,await this.loadData())}
async saveSettings(){await this.saveData(this.settings),this.refreshStyles()}
async toggleVisibility(){this.settings.enabled=!this.settings.enabled,await this.saveSettings(),this.updateStatusBarItem(),this.updateRibbonIcon(),this.applyStyles(),this.showNotice()}
async toggleCursorReveal(){this.settings.revealOnCursor=!this.settings.revealOnCursor,await this.saveSettings(),new i.Notice("光标行显示: "+(this.settings.revealOnCursor?"开启（可能闪烁）":"关闭（稳定）"))}
async toggleHoverReveal(){this.settings.revealOnHover=!this.settings.revealOnHover,await this.saveSettings(),new i.Notice("悬停显示: "+(this.settings.revealOnHover?"开启":"关闭"))}
showNotice(){var t=this.settings.enabled?"隐藏":"显示",e=[];this.settings.enabled&&!0;var o=e.length>0?"Markdown 标记已"+t+" ("+e.join(", ")+")":"Markdown 标记已"+t;new i.Notice(o,2e3)}
createStatusBarItem(){this._statusBarItem&&this._statusBarItem.remove(),this._statusBarItem=this.addStatusBarItem(),this._statusBarItem.addClass("mv-status-bar-item"),this.updateStatusBarItem(),this._statusBarItem.addEventListener("click",()=>{this.toggleVisibility()})}
updateStatusBarItem(){if(!this._statusBarItem)return;var t=this.settings.enabled?"👁️":"👁️‍🗨️",e=this.settings.enabled?"MD 隐藏中":"MD 显示中";this._statusBarItem.setText(t+" "+e),this.settings.enabled?this._statusBarItem.addClass("mv-active"):this._statusBarItem.removeClass("mv-active")}
removeStatusBarItem(){this._statusBarItem&&(this._statusBarItem.remove(),this._statusBarItem=null)}
createRibbonIcon(){this._ribbonIcon=this.addRibbonIcon("eye","切换 Markdown 标记可见性",()=>this.toggleVisibility()),this.updateRibbonIcon()}
updateRibbonIcon(){this._ribbonIcon&&(this.settings.enabled?this._ribbonIcon.addClass("mv-ribbon-active"):this._ribbonIcon.removeClass("mv-ribbon-active"))}
removeRibbonIcon(){this._ribbonIcon=null}
_setClass(t,e,o){o?t.classList.add(e):t.classList.remove(e)}
applyStyles(){var t=document.body;if(!this.settings.enabled){t.classList.remove("markdown-visibility-enabled");return}t.classList.add("markdown-visibility-enabled"),this._setClass(t,"mv-hide-headers",this.settings.hideHeaders),this._setClass(t,"mv-hide-bold",this.settings.hideBold),this._setClass(t,"mv-hide-italic",this.settings.hideItalic),this._setClass(t,"mv-hide-strikethrough",this.settings.hideStrikethrough),this._setClass(t,"mv-hide-highlight",this.settings.hideHighlight),this._setClass(t,"mv-hide-links",this.settings.hideLinks),this._setClass(t,"mv-hide-code",this.settings.hideCode),this._setClass(t,"mv-hide-quotes",this.settings.hideQuotes),this._setClass(t,"mv-hide-lists",this.settings.hideLists),this._setClass(t,"mv-hide-task",this.settings.hideTask),this._setClass(t,"mv-hide-tags",this.settings.hideTags),this._setClass(t,"mv-hide-hr",this.settings.hideHr),this._setClass(t,"mv-hide-table",this.settings.hideTable),this._setClass(t,"mv-hide-footnote",this.settings.hideFootnote),this._setClass(t,"mv-cursor-reveal",this.settings.revealOnCursor),this._setClass(t,"mv-hover-reveal",this.settings.revealOnHover)}
removeStyles(){var t=document.body;t.classList.remove("markdown-visibility-enabled"),["mv-hide-headers","mv-hide-bold","mv-hide-italic","mv-hide-strikethrough","mv-hide-highlight","mv-hide-links","mv-hide-code","mv-hide-quotes","mv-hide-lists","mv-hide-task","mv-hide-tags","mv-hide-hr","mv-hide-table","mv-hide-footnote","mv-cursor-reveal","mv-hover-reveal"].forEach(e=>t.classList.remove(e))}
refreshStyles(){this.removeStyles(),this.applyStyles(),this.updateStatusBarItem(),this.updateRibbonIcon()}
debouncedRefreshStyles(){this._debounceTimer&&clearTimeout(this._debounceTimer);var t=this;this._debounceTimer=setTimeout(function(){t.refreshStyles(),t._debounceTimer=null},100)}};

/* nosourcemap */
